project:
  type: book

book:
  title: "Algorithms and Data Structures SoSe 25 Solutions"
  author: "Igor Dimitrov"
  date: "12/18/2024"
  chapters:
    - index.qmd
    - sh01/sh01.ipynb
    - sh02/sh02.ipynb
    - sh03/03.ipynb
  downloads: ["pdf"]
  page-navigation: true

number-depth: 1

bibliography: references.bib

csl: nature.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    number-depth: 1



